feat: allow executor overrides in all orbs
talkiq/circleci-orbs pull request #88
Opened 2022-06-08 20:26 UTC by TheKevJames

## Summary
#86 was incredibly useful for allowing us to override executors rather than
copy-pasting a bunch of jobs. Executors are also supported by Renovate, which
means we caught some accidental usages of outdated images.

Apply those changes to everything!

* deployer, docker, docs, gcloud, linter: make the above change. BREAKING.
* notifier: make the above change. Not breaking.
* gcloud: additionally allow the docker server version to be specified.

### Checklist
- [x] My comments/docstrings/type hints are clear
- [x] I've written new tests or this change does not need them
- [ ] I've tested this manually
- [x] The architecture diagrams have been updated, if need be
- [x] I've included any special rollback strategies above
- [x] Any relevant metrics/monitors/SLOs have been added or modified
- [x] I've notified all relevant stakeholders of the change
- [x] I've updated .github/CODEOWNERS, if relevant

2022-08-10 13:21 UTC, caseydialpad requested changes
There appear to be three locations requiring `executor: <<parameters.executor>>`.

2022-08-10 13:21 UTC, caseydialpad commented on gcloud/orb.yaml
> +        type: executor
The `executor` doesn't appear to get used in this job

2022-08-10 13:21 UTC, caseydialpad commented on gcloud/orb.yaml
> +        type: executor
Perhaps double check this one as well.

2022-08-10 13:21 UTC, caseydialpad commented on gcloud/orb.yaml
> +        type: executor
Perhaps I'm rusty with how thee are used as my intuition says the line should look like `executor: <<parameters.executor>>`.

2022-08-31 12:33 UTC, TheKevJames commented
@caseydialpad you were indeed correct on all accounts, good eyes

2022-09-07 12:48 UTC, merged