Leanaha/run poetry with extras
talkiq/circleci-orbs pull request #89
Opened 2022-06-13 20:18 UTC by leanaha

## Summary

I added a new job inside the poetry orb to run `poetry install` with an extra parameter (i.e. `-E` flag).  

### Checklist

- [ ] My comments/docstrings/type hints are clear
- [ ] I've written new tests or this change does not need them
- [ ] I've tested this manually
- [ ] The architecture diagrams have been updated, if need be
- [ ] I've included any special rollback strategies above
- [ ] Any relevant metrics/monitors/SLOs have been added or modified
- [ ] I've notified all relevant stakeholders of the change
- [ ] I've updated .github/CODEOWNERS, if relevant

2022-06-13 20:30 UTC, jonathan-johnston requested changes

2022-06-13 20:31 UTC, jonathan-johnston commented on poetry/orb.yaml
> +          working_directory: <<parameters.cwd>>
To make this possible, you would have to set the `default` value of `extra` to `''` (an empty string) so that it evaluates as false by default.

2022-06-13 20:52 UTC, leanaha commented on poetry/orb.yaml
> +          working_directory: <<parameters.cwd>>
I changed it accordingly.

2022-06-14 14:10 UTC, jonathan-johnston approved these changes
Thanks Lean!

2022-06-14 15:20 UTC, merged